pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                script {
                    if (sh(returnStatus: true, script: 'mvn -q -DforceStdout help:evaluate -Dexpression=project.version').trim() != '1.0-SNAPSHOT') {
                        error 'Project version is not 1.0-SNAPSHOT. Aborting pipeline!'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
